### ISSUE TITLE
Can anybody help me with what this error means?

### ISSUE THREAD

**Issue by TheHexiz** [n00mkrad/text2image-gui#46]
I haven't spent much time with a pc for a couple years, and i was wondering what this/these error(s) mean.
any help would be appreciated!
-----------------------------------------------------------------------------------------------------------------------------------

Unhandled Thread Exception!

Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

Stack Trace:
   at StableDiffusionGui.ExtensionMethods.MatchesWildcard(String str, String wildcard)
   at StableDiffusionGui.Ui.MainUi.DoStartupChecks()
   at StableDiffusionGui.MainForm.<Initialize>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StableDiffusionGui.MainForm.<MainForm_Shown>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by n00mkrad** [comment]
It means a DLL that usually comes with Windows is missing.

What version are you on?

In newer versions, I include the DLL with the program so it should not be an issue...

**Comment by TheHexiz** [comment]
I was trying to run it on my old Laaptop, it runs Windows 7. lol

**Comment by n00mkrad** [comment]
No support for Win7

**Comment by TheHexiz** [comment]
okay Thank you! i will get it on my other one then.

I appreciate it.
