### ISSUE TITLE
No Images generated

### ISSUE THREAD

**Issue by AndreHero007** [n00mkrad/text2image-gui#49]
The "No Images Generated" error always appears when I use the "ONNX" option.
My device:
*RX 580 8GB
* I3-9100F
* 16GB RAM

What I already tried and it didn't work:
* Several different values for "Generation Steps".
* Several different values for "CFG Scale".
* Several different resolutions.
* Two different ONNX models.

I tried generating pictures with the "CUDA" options using just the CPU and it worked.
So the "No Images Generated" only appears when I use ONNX.

**Comment by caiocenlep** [comment]
same here

**Comment by n00mkrad** [comment]
Post your `sd` log files

**Comment by caiocenlep** [comment]
> Post your `sd` log files

[00000021] [12-27-2022 13:39:21] 2 0 2 2 - 1 2 - 2 7   1 3 : 3 9 : 2 1 . 1 7 8 3 6 4 6   [ W : o n n x r u n t i m e : ,   i n f e r e n c e _ s e s s i o n . c c : 4 9 1   o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : R e g i s t e r E x e c u t i o n P r o v i d e r ]   H a v i n g   m e m o r y   p a t t e r n   e n a b l e d   i s   n o t   s u p p o r t e d   w h i l e   u s i n g   t h e   D M L   E x e c u t i o n   P r o v i d e r .   S o   d i s a b l i n g   i t   f o r   t h i s   s e s s i o n   s i n c e   i t   u s e s   t h e   D M L   E x e c u t i o n   P r o v i d e r . 
[00000022] [12-27-2022 13:39:22]  2 0 2 2 - 1 2 - 2 7   1 3 : 3 9 : 2 2 . 3 5 5 4 2 0 8   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 0 3 0   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   S o m e   n o d e s   w e r e   n o t   a s s i g n e d   t o   t h e   p r e f e r r e d   e x e c u t i o n   p r o v i d e r s   w h i c h   m a y   o r   m a y   n o t   h a v e   a n   n e g a t i v e   i m p a c t   o n   p e r f o r m a n c e .   e . g .   O R T   e x p l i c i t l y   a s s i g n s   s h a p e   r e l a t e d   o p s   t o   C P U   t o   i m p r o v e   p e r f . 
[00000023] [12-27-2022 13:39:22]  2 0 2 2 - 1 2 - 2 7   1 3 : 3 9 : 2 2 . 3 5 5 7 8 6 7   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 0 3 2   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   R e r u n n i n g   w i t h   v e r b o s e   o u t p u t   o n   a   n o n - m i n i m a l   b u i l d   w i l l   s h o w   n o d e   a s s i g n m e n t s . 
[00000024] [12-27-2022 13:39:27]  2 0 2 2 - 1 2 - 2 7   1 3 : 3 9 : 2 7 . 0 5 5 4 8 1 0   [ E : o n n x r u n t i m e : ,   i n f e r e n c e _ s e s s i o n . c c : 1 5 0 0   o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : I n i t i a l i z e : : < l a m b d a _ d 6 7 c d e 1 8 8 9 1 e 9 d 3 1 1 7 3 9 1 6 2 a 2 b 4 a b a 6 d > : : o p e r a t o r   ( ) ]   E x c e p t i o n   d u r i n g   i n i t i a l i z a t i o n :   D : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ p r o v i d e r s \ d m l \ D m l E x e c u t i o n P r o v i d e r \ s r c \ E x e c u t i o n P r o v i d e r . c p p ( 5 6 3 ) \ o n n x r u n t i m e _ p y b i n d 1 1 _ s t a t e . p y d ! 0 0 0 0 7 F F 8 A 9 D 3 8 B 0 1 :   ( c a l l e r :   0 0 0 0 7 F F 8 A 9 D 3 8 8 A 2 )   E x c e p t i o n ( 2 )   t i d ( 2 9 2 0 )   8 0 0 7 0 0 0 E   R e c u r s o s   d e   m e m ýÿr i a   i n s u f i c i e n t e s   d i s p o n ýÿv e i s   p a r a   c o n c l u i r   a   o p e r a ýÿýÿo . 
[00000025] [12-27-2022 13:39:27]  
[00000026] [12-27-2022 13:39:27]  
[00000027] [12-27-2022 13:39:27]  Traceback (most recent call last):
[00000028] [12-27-2022 13:39:27]   File "C:\SD-GUI-1.8.0\Data\repo\sd_onnx\sd_onnx.py", line 58, in <module>
[00000029] [12-27-2022 13:39:27]     pipe = OnnxStableDiffusionPipeline.from_pretrained(opt.mdlpath, provider=prov, safety_checker=None)
[00000030] [12-27-2022 13:39:27]   File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\diffusers\pipeline_utils.py", line 709, in from_pretrained
[00000031] [12-27-2022 13:39:27]     loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
[00000032] [12-27-2022 13:39:27]   File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\diffusers\onnx_utils.py", line 206, in from_pretrained
[00000033] [12-27-2022 13:39:27]     return cls._from_pretrained(
[00000034] [12-27-2022 13:39:27]   File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\diffusers\onnx_utils.py", line 173, in _from_pretrained
[00000035] [12-27-2022 13:39:27]     model = OnnxRuntimeModel.load_model(
[00000036] [12-27-2022 13:39:27]   File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\diffusers\onnx_utils.py", line 78, in load_model
[00000037] [12-27-2022 13:39:27]     return ort.InferenceSession(path, providers=[provider], sess_options=sess_options)
[00000038] [12-27-2022 13:39:27]   File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
[00000039] [12-27-2022 13:39:27]     self._create_inference_session(providers, provider_options, disabled_optimizers)
[00000040] [12-27-2022 13:39:27]   File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
[00000041] [12-27-2022 13:39:27]     sess.initialize_session(providers, provider_options, disabled_optimizers)
[00000042] [12-27-2022 13:39:27] onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException

**Comment by n00mkrad** [comment]
> > Post your `sd` log files
> 
> [00000021] [12-27-2022 13:39:21] 2 0 2 2 - 1 2 - 2 7 1 3 : 3 9 : 2 1 . 1 7 8 3 6 4 6 [ W : o n n x r u n t i m e : , i n f e r e n c e _ s e s s i o n . c c : 4 9 1 o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : R e g i s t e r E x e c u t i o n P r o v i d e r ] H a v i n g m e m o r y p a t t e r n e n a b l e d i s n o t s u p p o r t e d w h i l e u s i n g t h e D M L E x e c u t i o n P r o v i d e r . S o d i s a b l i n g i t f o r t h i s s e s s i o n s i n c e i t u s e s t h e D M L E x e c u t i o n P r o v i d e r . [00000022] [12-27-2022 13:39:22] 2 0 2 2 - 1 2 - 2 7 1 3 : 3 9 : 2 2 . 3 5 5 4 2 0 8 [ W : o n n x r u n t i m e : , s e s s i o n _ s t a t e . c c : 1 0 3 0 o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ] S o m e n o d e s w e r e n o t a s s i g n e d t o t h e p r e f e r r e d e x e c u t i o n p r o v i d e r s w h i c h m a y o r m a y n o t h a v e a n n e g a t i v e i m p a c t o n p e r f o r m a n c e . e . g . O R T e x p l i c i t l y a s s i g n s s h a p e r e l a t e d o p s t o C P U t o i m p r o v e p e r f . [00000023] [12-27-2022 13:39:22] 2 0 2 2 - 1 2 - 2 7 1 3 : 3 9 : 2 2 . 3 5 5 7 8 6 7 [ W : o n n x r u n t i m e : , s e s s i o n _ s t a t e . c c : 1 0 3 2 o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ] R e r u n n i n g w i t h v e r b o s e o u t p u t o n a n o n - m i n i m a l b u i l d w i l l s h o w n o d e a s s i g n m e n t s . [00000024] [12-27-2022 13:39:27] 2 0 2 2 - 1 2 - 2 7 1 3 : 3 9 : 2 7 . 0 5 5 4 8 1 0 [ E : o n n x r u n t i m e : , i n f e r e n c e _ s e s s i o n . c c : 1 5 0 0 o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : I n i t i a l i z e : : < l a m b d a _ d 6 7 c d e 1 8 8 9 1 e 9 d 3 1 1 7 3 9 1 6 2 a 2 b 4 a b a 6 d > : : o p e r a t o r ( ) ] E x c e p t i o n d u r i n g i n i t i a l i z a t i o n : D : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ p r o v i d e r s \ d m l \ D m l E x e c u t i o n P r o v i d e r \ s r c \ E x e c u t i o n P r o v i d e r . c p p ( 5 6 3 ) \ o n n x r u n t i m e _ p y b i n d 1 1 _ s t a t e . p y d ! 0 0 0 0 7 F F 8 A 9 D 3 8 B 0 1 : ( c a l l e r : 0 0 0 0 7 F F 8 A 9 D 3 8 8 A 2 ) E x c e p t i o n ( 2 ) t i d ( 2 9 2 0 ) 8 0 0 7 0 0 0 E R e c u r s o s d e m e m ýÿr i a i n s u f i c i e n t e s d i s p o n ýÿv e i s p a r a c o n c l u i r a o p e r a ýÿýÿo . [00000025] [12-27-2022 13:39:27] [00000026] [12-27-2022 13:39:27] [00000027] [12-27-2022 13:39:27] Traceback (most recent call last): [00000028] [12-27-2022 13:39:27] File "C:\SD-GUI-1.8.0\Data\repo\sd_onnx\sd_onnx.py", line 58, in [00000029] [12-27-2022 13:39:27] pipe = OnnxStableDiffusionPipeline.from_pretrained(opt.mdlpath, provider=prov, safety_checker=None) [00000030] [12-27-2022 13:39:27] File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\diffusers\pipeline_utils.py", line 709, in from_pretrained [00000031] [12-27-2022 13:39:27] loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs) [00000032] [12-27-2022 13:39:27] File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\diffusers\onnx_utils.py", line 206, in from_pretrained [00000033] [12-27-2022 13:39:27] return cls._from_pretrained( [00000034] [12-27-2022 13:39:27] File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\diffusers\onnx_utils.py", line 173, in _from_pretrained [00000035] [12-27-2022 13:39:27] model = OnnxRuntimeModel.load_model( [00000036] [12-27-2022 13:39:27] File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\diffusers\onnx_utils.py", line 78, in load_model [00000037] [12-27-2022 13:39:27] return ort.InferenceSession(path, providers=[provider], sess_options=sess_options) [00000038] [12-27-2022 13:39:27] File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in **init** [00000039] [12-27-2022 13:39:27] self._create_inference_session(providers, provider_options, disabled_optimizers) [00000040] [12-27-2022 13:39:27] File "C:\SD-GUI-1.8.0\Data\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session [00000041] [12-27-2022 13:39:27] sess.initialize_session(providers, provider_options, disabled_optimizers) [00000042] [12-27-2022 13:39:27] onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException

What's your GPU? Might be too old or not have enough VRAM

**Comment by caiocenlep** [comment]
> What's your GPU? Might be too old or not have enough VRAM

RX550 4GB

**Comment by n00mkrad** [comment]
> > What's your GPU? Might be too old or not have enough VRAM
> 
> RX550 4GB

4 GB is most likely not enough.

**Comment by caiocenlep** [comment]
> > > What's your GPU? Might be too old or not have enough VRAM
> > 
> > 
> > RX550 4GB
> 
> 4 GB is most likely not enough.

ok, tkx
but op GPU is 8gb

**Comment by WhiteAssassins** [comment]
Tengo exactamente el mismo error con una RX 580 de 8GB.
